#+TODO: TODO(t) WIP(r) UNDER-REVIEW(b) BLOCK(k) | DELEGATED(d) FIXED(f) INVALID(i) DONE(o)

* Open CI Syncs

** <2020-07-15 mié>
*** force push those patchset with CI failure. CI is broken so failures are still there
*** BLOCK CI is broken, missing libraries linaro release 19_06 https://projects.linaro.org/browse/LSS-1500
**** BLOCK https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/4554
**** BLOCK https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/4640
*** BLOCK static checks for TF-M. email sent to arm team about this topic and how to approach it.
		
*** test levels

** <2020-07-29 mié>
*** TF-A is now working
*** TF-M is still broken. 'FYI, Ben has worked out why the bionic label is missing and why the zombie jobs are happening
It's a problem with "K8", Kubernetes / fargate / ec2 magic'
*** lots of duplicates
*** FVP device
*** check this ticket https://projects.linaro.org/browse/LSS-1430
*** TODO submit a lava request manually using artefacts
*** DONE update the CI page with all of the links and review blocks (ticket ids)
*** TODO make sure all blocked tasks is not from us


** <2020-08-04 mar>

*** first estimation of number of platforms (PLAT) that are covereted of tf-a-ci-scripts

#+BEGIN_SRC bash
# list PLAT's 
cd ~/repos/TF-A/tf-a-ci-scripts && grep -h -o 'PLAT=[[:alnum:]]*' tf_config/* | sort | uniq 
#+END_SRC

#+RESULTS:
| PLAT=a3700       |
| PLAT=a5ds        |
| PLAT=a70x0       |
| PLAT=a80x0       |
| PLAT=agilex      |
| PLAT=arm         |
| PLAT=axg         |
| PLAT=corstone700 |
| PLAT=fvp         |
| PLAT=g12a        |
| PLAT=gxbb        |
| PLAT=gxl         |
| PLAT=hikey       |
| PLAT=hikey960    |
| PLAT=imx8mm      |
| PLAT=imx8mn      |
| PLAT=imx8mq      |
| PLAT=imx8qm      |
| PLAT=imx8qx      |
| PLAT=juno        |
| PLAT=k3          |
| PLAT=ls1043      |
| PLAT=mt6795      |
| PLAT=mt8173      |
| PLAT=mt8183      |
| PLAT=n1sdp       |
| PLAT=picopi      |
| PLAT=poplar      |
| PLAT=px30        |
| PLAT=qemu        |
| PLAT=rcar        |
| PLAT=rde1edge    |
| PLAT=rdn1edge    |
| PLAT=rk3288      |
| PLAT=rk3328      |
| PLAT=rk3368      |
| PLAT=rk3399      |
| PLAT=rpi3        |
| PLAT=rpi4        |
| PLAT=sgi575      |
| PLAT=sgm775      |
| PLAT=stingray    |
| PLAT=stm32mp1    |
| PLAT=stratix10   |
| PLAT=sun50i      |
| PLAT=synquacer   |
| PLAT=tc0         |
| PLAT=tegra       |
| PLAT=uniphier    |
| PLAT=versal      |
| PLAT=warp7       |
| PLAT=zynqmp      |

#+BEGIN_SRC bash
#count PLAT's
cd ~/repos/TF-A/tf-a-ci-scripts && grep -h -o 'PLAT=[[:alnum:]]*' tf_config/* | sort | uniq | wc
#+END_SRC

#+RESULTS:
: 52      52     603



*** status of '** WIP FVP Support <2020-07-30 jue> <2020-07-31 vie> <2020-07-29 mié> <2020-08-03 lun> <2020-08-04 mar>:fvp:tf_m:tf_m_id3:tf_a_id26:'
**** WIP for a single model (run_config)
**** LAVA yaml produced but not tested
***** status of the staging instance? does it have access to private docker registry?
***** TODO before testing on LAVA, testing will be done locally **without** using LAVA and just calling the model binary
***** TODO RFC patchset to be sent today. This is important to make sure we are in the right path (and not reinventing the wheel again)
***** this work required lots of reverse engineering and will greatly help the last taks of this phase: documentation (lots of documentation required)


*** status of '** TODO arm static checks on tf-m patchsets https://review.trustedfirmware.org/c/ci/tf-m-ci-scripts/+/4972 :tf_m_ci_scripts:'
**** ARM (Karl) required a minor rework of the patchset: two patches (commits): 1. the 'copy & paste' from TF-A scripts and 2. the changes done to adopt to TF-M
**** There othe check pending is coverity on TF-M. Coverity is a tree checker, not a patch checker. Let's make sure Coverity fits on TF-M before doing this work. 

** <2020-08-12 mié>

*** TODO no work done on FVP licenses, alias FlexLM licenses

*** WIP started reading the documentation the share documentation, specially tf-a-ci-doc.sh. these was shared to Leo some time ago but did not read it: I was doing reverse engineering
**** document is still mostly valid (though I have not gone in detail)
**** will be used as a main reference
***** some documentation patcheds (readmes) have already land to master and my plan is to start creating rst files, this will
help me understanding all framework and less work for last milestone.

**** Impact on previous work based on tf-a-ci-scripts sync: NONE
**** (First impression) Impact on previous work based on tf-a-job-configs sync: 

***** ARM CI jobs 

 pros

 - Jobs call multiple scripts instead allowing much higher and simpler Jenkins Job Parallelization
 - ARM Jobs already in sync with tf-a-ci-scripts so no need to do 'much' work from linaro
 - most important: this is the ARM way and it has been tested with much more load so we indirectly know that it 'scales well'

 cons

 - job migration/replacement
   - remove all hardcoded links
   - test


**** Open CI jobs

pros

- a bit more familiar that ARM jobs
- just one single script is called (run_local_ci.sh) and all work is done by latter

cons

- failure debugging probably is more difficult because a single script does all
- most important: this is not what ARM wants.
  

***** ARM CI Job migration: time estimates

* Job migration. 2 weeks
  
** Linaro has all ARM CI jobs specs that need to be migrated into the Open CI.

** Remove all hard coded paths

** Test migration (staging instance)


* FVP support (remaining work): 1 week

** RFC patchset already available for tf-a-ci-scripts. Although it is a RFC (request for comments), it is looking good and targeting master soon. Needs another +1
** Push containers with FVP models to private registry
** Test full CI cycle (tf-ci-gateway -> tf-worker -> tf-build-for-lava -> LAVA) at least with one model
** This task depends on the job migration, so the latter must be finished first.


* Previous work (to be reworked): 3 weeks

** split test_groups parameters: 1 week
https://review.trustedfirmware.org/c/ci/tf-a-job-configs/+/4917

This work impacts several ID's:
M2 Ability to build multiple configurations of TF-A (TF-A ID9)
M3 & M4 Ability to build multiple configurations of TF-A Tests (TF-A ID12)
needs to be re-done.

** Define trigger and tf-a-test job configs alias CI loop: 2 weeks
https://review.trustedfirmware.org/c/ci/tf-a-job-configs/+/4873
this work impacts: Create CI loop for TF-A Tests (TF-A ID2)




https://review.trustedfirmware.org/q/project:ci%252Ftf-a-job-configs+status:open





* TODO send to glen a brief resume of the above

* TODO check into TF-M issue, set docker registry and push docker container https://projects.linaro.org/browse/LSS-1525

